### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by j-lootens** [mjq11302010044/TATT#1]
Would it be possible to make a pre-trained model available?

**Comment by mjq11302010044** [comment]
@TheNoodleNinja Sorry, we don't actually need a pre-trained model, you can directly train the model on the TextZoom dataset.

**Comment by j-lootens** [comment]
Np but it might be useful for people who only have limited VRAM or no dedicated GPU at all.

**Comment by mjq11302010044** [comment]
@TheNoodleNinja If you mean the model trained TextZoom, that will be added to the release. Thanks for your advice though. :)
