### ISSUE TITLE
images_sr = model(images_hr)

### ISSUE THREAD

**Issue by chnoguchi** [mjq11302010044/TATT#13]
At line 1734 in `interfaces/super_resolution.py`, 
```
images_sr = model(images_hr)
```
It seems that HR images are input into the model. Is this correct specification?

**Comment by mjq11302010044** [comment]
@chnoguchi Hi, thanks for pointing out that problem, this piece of code is not actually used on our evaluation. Please check eval() function in super_resolution.py. You can directly remove this piece and the project will still perform normally.
