### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by chhkang** [mjq11302010044/TATT#9]
Accepted from CVPR 2022 a long time ago, and still there is no pertained model for TextZoom. 
Authors mentioned this problem in closed issue #1, said they will release pre-trained model in later release version, but still don't upload checkpoint for measuring their performance.

**Comment by mjq11302010044** [comment]
This guy @chhkang sent me an email with the trained-model request, I don't know why he still raises this issue after I provide him a shared link through email. As I said in #4 , anyone can have access to our parameters by emailing a request.
